# SPDX-License-Identifier: MIT
# Dependabot: keep pinned GitHub Actions current.
# Note: SwiftPM is not yet supported by Dependabot, and this project ships
# zero third-party Swift dependencies, so only github-actions is configured.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - github-actions
